// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2tdQqL9_2wtw7WKvJcOxPpXQ72vQ7lPs',
    appId: '1:381843955978:web:ea04e41347739963371af3',
    messagingSenderId: '381843955978',
    projectId: 'd-zuze',
    authDomain: 'd-zuze.firebaseapp.com',
    storageBucket: 'd-zuze.appspot.com',
    measurementId: 'G-6VCN469VJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijrFB2MDGiX66Rd3d32L3EA4mrOP_Ijo',
    appId: '1:381843955978:android:b5410eec262bce8a371af3',
    messagingSenderId: '381843955978',
    projectId: 'd-zuze',
    storageBucket: 'd-zuze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2CJVcoW4P9kSqrdIuDs6WdmZEQHWG7c',
    appId: '1:381843955978:ios:18cb4934404c366c371af3',
    messagingSenderId: '381843955978',
    projectId: 'd-zuze',
    storageBucket: 'd-zuze.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2CJVcoW4P9kSqrdIuDs6WdmZEQHWG7c',
    appId: '1:381843955978:ios:18cb4934404c366c371af3',
    messagingSenderId: '381843955978',
    projectId: 'd-zuze',
    storageBucket: 'd-zuze.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2tdQqL9_2wtw7WKvJcOxPpXQ72vQ7lPs',
    appId: '1:381843955978:web:8a66df4974636636371af3',
    messagingSenderId: '381843955978',
    projectId: 'd-zuze',
    authDomain: 'd-zuze.firebaseapp.com',
    storageBucket: 'd-zuze.appspot.com',
    measurementId: 'G-XJ23BVXLT2',
  );
}
